### ISSUE TITLE
criar dicionário de dados

### ISSUE THREAD

**Issue by kauanfontanela** [kauanfontanela/gerenciamento-cafeteria-abp2023#2]

**Comment by LucasAAnjos** [comment]
Versão 0 criada, estando pendente as tabelas de pagamento e avaliacao, além das últimas alterações realizadas no ER.
[V0.xlsx](https://github.com/kauanfontanela/gerenciamento-cafeteria-abp2023/files/13462591/V0.xlsx)

**Comment by tamiriel** [comment]
Irei atualizar o Dicionário assim que o modelo físico tiver sido revisado.
Segue o link para edições futuras: https://1drv.ms/x/s!Atb5Pj9kgzdLpwigyey_WS-U1ilN?e=oGKL1p

**Comment by LucasMeller13** [comment]
modelo físico revisado e finalizado

**Comment by tamiriel** [comment]
Revisão do dicionário de dados finalizada
