### ISSUE TITLE
criar modelo físico

### ISSUE THREAD

**Issue by kauanfontanela** [kauanfontanela/gerenciamento-cafeteria-abp2023#4]

**Comment by LucasMeller13** [comment]
O que acham desse modelo?

![Imagem do WhatsApp de 2023-11-24 à(s) 20 01 29_21ed60e7](https://github.com/kauanfontanela/gerenciamento-cafeteria-abp2023/assets/43608590/611d401f-412d-4388-a015-bfb4c8d66adb)

**Comment by LucasMeller13** [comment]
O que acham desse modelo? 
![Imagem do WhatsApp de 2023-11-24 à(s) 20 30 50_eac47e77](https://github.com/kauanfontanela/gerenciamento-cafeteria-abp2023/assets/43608590/5b68aa84-7979-40fc-9e66-27e017b7bcd1)

**Comment by LucasMeller13** [comment]
Primeira versão modelo físico, faltando desenvolver entidade "item" para alocação das colunas nome e preço.
![Imagem do WhatsApp de 2023-11-24 à(s) 20 30 50_2d6b79c2](https://github.com/kauanfontanela/gerenciamento-cafeteria-abp2023/assets/43608590/9d0d8c06-e67c-4cc5-822d-c6d23778031d)

**Comment by LucasMeller13** [comment]
Segunda versão modelo físico, entidade item adicionada.
![Imagem do WhatsApp de 2023-11-24 à(s) 20 50 05_d1af67f7](https://github.com/kauanfontanela/gerenciamento-cafeteria-abp2023/assets/43608590/5ca22a7e-7b18-4db9-b913-fc89b006d30e)

**Comment by Virtuosinh0** [comment]
Empecilhos no funcionamento do Banco:

cartao & beneficios
Juntar a tabela cartao e benefícios para ser uma tabela de cliente

pagamento
Adicionar codigo cliente (FK da tabela cliente) para utilizar os beneficios no pagamento

menu & item
Agregar a tabela item no menu (codigo_menu, nome, preço)

pedido
remover codigo_menu_fk

menu_item_pedido
remover a tabela

item_pedido
remover o codigo_item_pk e adicionar o pedido_fk (sugiro renomear a tabela para pedido_menu)

**Comment by Virtuosinh0** [comment]
pedido_menu
colocar a coluna codigo_menu_fk

**Comment by LucasMeller13** [comment]
Terceira versão modelo físico, mudança nas entidades e relacionamentos.
![image](https://github.com/kauanfontanela/gerenciamento-cafeteria-abp2023/assets/43608590/500d6f34-d59a-41d3-860c-a9b57db112fe)

**Comment by tamiriel** [comment]
Mudar o nome da coluna data_criacao na tabela cliente para data_cadastro

**Comment by tamiriel** [comment]
Mudar o tipo de dado da coluna codigo_cliente para char(11)
